# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: add.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='add.proto',
  package='add',
  syntax='proto3',
  serialized_pb=_b('\n\tadd.proto\x12\x03\x61\x64\x64\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08\x41\x64\x64Reply\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x32\x31\n\x03\x41\x64\x64\x12*\n\x06\x41\x64\x64Two\x12\x0f.add.AddRequest\x1a\r.add.AddReply\"\x00\x62\x06proto3')
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='add.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='add.AddRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='add.AddRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=52,
)


_ADDREPLY = _descriptor.Descriptor(
  name='AddReply',
  full_name='add.AddReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='add.AddReply.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddReply'] = _ADDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'add_pb2'
  # @@protoc_insertion_point(class_scope:add.AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddReply = _reflection.GeneratedProtocolMessageType('AddReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDREPLY,
  __module__ = 'add_pb2'
  # @@protoc_insertion_point(class_scope:add.AddReply)
  ))
_sym_db.RegisterMessage(AddReply)



_ADD = _descriptor.ServiceDescriptor(
  name='Add',
  full_name='add.Add',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=79,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTwo',
    full_name='add.Add.AddTwo',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADD)

DESCRIPTOR.services_by_name['Add'] = _ADD

# @@protoc_insertion_point(module_scope)
